version: "3.7"
services:
  database:
    image: postgres:latest
    restart: on-failure
    volumes:
      - ./docker/db:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_USER}
      PGDATA: /var/lib/postgres
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - database
  nginx:
    image: nginx:1.17.8-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - './app:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "${NGINX_PORT}:80"
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './app:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: ${LOCAL_USER}