#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_login:
  path: /api/login
  methods:  [POST]

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
#api:
#  prefix: /api
#  resource: '../src/Controller/Api'