#index:
#    path: /
#    controller: App\Controller\DefaultController::index

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
api_login:
  path: /api/login
  methods: POST
api_user_activation:
  path: /api/activate-user
  methods: POST